workflows:
  ultra_python_runner:
    name: Ultra Python Runner
    max_build_duration: 60

    environment:
      xcode: latest

    scripts:
      - name: Check project files
        script: |
          echo "Project files:"
          ls -la

      - name: Install Python & dependencies
        script: |
          python3 --version
          python3 -m pip install --upgrade pip
          python3 -m pip install python-telegram-bot aiohttp pymongo pytz psutil

      - name: Give permission to binary
        script: |
          if [ -f "ultra" ]; then
            chmod +x ultra
          fi

      - name: Run ultra.py
        script: |
          python3 ultra.py
